// Partwright brand mark — the voxel "P" rendered as an app-icon tile (amber on
// a dark rounded square). Used wherever the mark sits beside the "Partwright"
// wordmark (landing hero, toolbar, catalog, what's-new, about modal); the tile
// container keeps it from reading as the leading "P" of the word. Keep this in
// sync with public/favicon.svg / public/og-image.svg (hand-duplicated rasters).
//
// Geometry: an oblique-projection voxel P (cube grid, lit top→front→side),
// generated by .plans/build-voxel-sets.mjs. Coordinates are in the inner
// 0–64 voxel space, placed inside the 104×104 tile via translate(4 6) scale(1.5).

let markSeq = 0;

const VOXEL_P_INNER = `
    <polygon points="24,47 24,53 28,50.6 28,44.6" fill="#b45309"/>
    <polygon points="18,47 24,47 28,44.6 22,44.6" fill="#fde68a"/>
    <polygon points="18,47 24,47 24,53 18,53" fill="#f59e0b"/>
    <polygon points="24,41 24,47 28,44.6 28,38.6" fill="#b45309"/>
    <polygon points="18,41 24,41 28,38.6 22,38.6" fill="#fde68a"/>
    <polygon points="18,41 24,41 24,47 18,47" fill="#f59e0b"/>
    <polygon points="24,35 24,41 28,38.6 28,32.6" fill="#b45309"/>
    <polygon points="18,35 24,35 28,32.6 22,32.6" fill="#fde68a"/>
    <polygon points="18,35 24,35 24,41 18,41" fill="#f59e0b"/>
    <polygon points="24,29 24,35 28,32.6 28,26.6" fill="#b45309"/>
    <polygon points="18,29 24,29 28,26.6 22,26.6" fill="#fde68a"/>
    <polygon points="18,29 24,29 24,35 18,35" fill="#f59e0b"/>
    <polygon points="30,29 30,35 34,32.6 34,26.6" fill="#b45309"/>
    <polygon points="24,29 30,29 34,26.6 28,26.6" fill="#fde68a"/>
    <polygon points="24,29 30,29 30,35 24,35" fill="#f59e0b"/>
    <polygon points="36,29 36,35 40,32.6 40,26.6" fill="#b45309"/>
    <polygon points="30,29 36,29 40,26.6 34,26.6" fill="#fde68a"/>
    <polygon points="30,29 36,29 36,35 30,35" fill="#f59e0b"/>
    <polygon points="42,29 42,35 46,32.6 46,26.6" fill="#b45309"/>
    <polygon points="36,29 42,29 46,26.6 40,26.6" fill="#fde68a"/>
    <polygon points="36,29 42,29 42,35 36,35" fill="#f59e0b"/>
    <polygon points="24,23 24,29 28,26.6 28,20.6" fill="#b45309"/>
    <polygon points="18,23 24,23 28,20.6 22,20.6" fill="#fde68a"/>
    <polygon points="18,23 24,23 24,29 18,29" fill="#f59e0b"/>
    <polygon points="42,23 42,29 46,26.6 46,20.6" fill="#b45309"/>
    <polygon points="36,23 42,23 46,20.6 40,20.6" fill="#fde68a"/>
    <polygon points="36,23 42,23 42,29 36,29" fill="#f59e0b"/>
    <polygon points="24,17 24,23 28,20.6 28,14.6" fill="#b45309"/>
    <polygon points="18,17 24,17 28,14.6 22,14.6" fill="#fde68a"/>
    <polygon points="18,17 24,17 24,23 18,23" fill="#f59e0b"/>
    <polygon points="42,17 42,23 46,20.6 46,14.6" fill="#b45309"/>
    <polygon points="36,17 42,17 46,14.6 40,14.6" fill="#fde68a"/>
    <polygon points="36,17 42,17 42,23 36,23" fill="#f59e0b"/>
    <polygon points="24,11 24,17 28,14.6 28,8.6" fill="#b45309"/>
    <polygon points="18,11 24,11 28,8.6 22,8.6" fill="#fde68a"/>
    <polygon points="18,11 24,11 24,17 18,17" fill="#f59e0b"/>
    <polygon points="30,11 30,17 34,14.6 34,8.6" fill="#b45309"/>
    <polygon points="24,11 30,11 34,8.6 28,8.6" fill="#fde68a"/>
    <polygon points="24,11 30,11 30,17 24,17" fill="#f59e0b"/>
    <polygon points="36,11 36,17 40,14.6 40,8.6" fill="#b45309"/>
    <polygon points="30,11 36,11 40,8.6 34,8.6" fill="#fde68a"/>
    <polygon points="30,11 36,11 36,17 30,17" fill="#f59e0b"/>
    <polygon points="42,11 42,17 46,14.6 46,8.6" fill="#b45309"/>
    <polygon points="36,11 42,11 46,8.6 40,8.6" fill="#fde68a"/>
    <polygon points="36,11 42,11 42,17 36,17" fill="#f59e0b"/>
    <polygon points="18,11 24,11 24,17 18,17" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="24,11 30,11 30,17 24,17" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="30,11 36,11 36,17 30,17" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="36,11 42,11 42,17 36,17" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="18,17 24,17 24,23 18,23" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="36,17 42,17 42,23 36,23" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="18,23 24,23 24,29 18,29" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="36,23 42,23 42,29 36,29" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="18,29 24,29 24,35 18,35" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="24,29 30,29 30,35 24,35" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="30,29 36,29 36,35 30,35" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="36,29 42,29 42,35 36,35" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="18,35 24,35 24,41 18,41" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="18,41 24,41 24,47 18,47" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <polygon points="18,47 24,47 24,53 18,53" fill="none" stroke="#5c2e05" stroke-width="0.5" stroke-opacity="0.55" stroke-linejoin="round"/>
    <path d="M18,11 L22,8.6 L28,8.6" fill="none" stroke="#fffbeb" stroke-width="0.7" stroke-linecap="round" opacity="0.7"/>
    <path d="M24,11 L28,8.6 L34,8.6" fill="none" stroke="#fffbeb" stroke-width="0.7" stroke-linecap="round" opacity="0.7"/>
    <path d="M30,11 L34,8.6 L40,8.6" fill="none" stroke="#fffbeb" stroke-width="0.7" stroke-linecap="round" opacity="0.7"/>
    <path d="M36,11 L40,8.6 L46,8.6" fill="none" stroke="#fffbeb" stroke-width="0.7" stroke-linecap="round" opacity="0.7"/>
    <path d="M24,29 L28,26.6 L34,26.6" fill="none" stroke="#fffbeb" stroke-width="0.7" stroke-linecap="round" opacity="0.7"/>
    <path d="M30,29 L34,26.6 L40,26.6" fill="none" stroke="#fffbeb" stroke-width="0.7" stroke-linecap="round" opacity="0.7"/>`;

/** The Partwright voxel-P mark as an app-icon tile, sized to `size`×`size` px. */
export function partwrightMarkSvg(size = 24): string {
  const id = `pwmark${++markSeq}`;
  return `<svg width="${size}" height="${size}" viewBox="0 0 104 104" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
  <defs>
    <linearGradient id="${id}tile" x1="0" y1="0" x2="104" y2="104" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#1c1408"/><stop offset="1" stop-color="#0a0703"/>
    </linearGradient>
    <clipPath id="${id}clip"><rect x="0" y="0" width="104" height="104" rx="24"/></clipPath>
  </defs>
  <rect x="0" y="0" width="104" height="104" rx="24" fill="url(#${id}tile)"/>
  <g clip-path="url(#${id}clip)"><g transform="translate(4 6) scale(1.5)">${VOXEL_P_INNER}
  </g></g>
  <rect x="1" y="1" width="102" height="102" rx="23" fill="none" stroke="#f59e0b" stroke-width="1.4" stroke-opacity="0.45"/>
</svg>`;
}
