// Turn a CharacterSpec into self-contained `api.sdf.figure` model code.
//
// The output follows the canonical figure recipe (see public/ai/figure.md):
// build a rig, build parts off it, weld the body, label regions, declare paint
// in code with `api.paint.label`, then hard-union and `.build()`. Eyes, lips and
// brows are unioned at the TOP level so each is a separately paintable label;
// the carved mouth is left off the assemble in favour of a paintable lip ridge.
//
// The generated code carries the spec as a `// @character v1 {json}` header so
// the panel round-trips it exactly, while the body stays ordinary, hand-editable
// figure code. Pure text generation (no DOM/engine) so it unit-tests in the
// vitest tier, like surfaceCodegen.ts.

import {
  type CharacterSpec,
  type Joint,
  encodeSpecComment,
} from './characterSpec';

/** Format a scalar for source output (numbers trimmed to 6 sig-figs). */
function fmt(v: number | boolean | string): string {
  if (typeof v === 'number') return String(Number(v.toPrecision(6)));
  if (typeof v === 'boolean') return String(v);
  return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** Render a record as a one-line object literal, skipping undefined values.
 *  Returns '' (not '{}') when every value was skipped, so callers can drop the
 *  options argument entirely for a clean default call. */
function obj(rec: Record<string, number | boolean | string | undefined>): string {
  const entries = Object.entries(rec).filter(([, v]) => v !== undefined) as [string, number | boolean | string][];
  if (entries.length === 0) return '';
  return `{ ${entries.map(([k, v]) => `${k}: ${fmt(v)}`).join(', ')} }`;
}

/** Emit a pose joint as an options object, keeping only non-zero fields. Returns
 *  null when the joint is fully neutral so the whole key can be omitted. */
function jointLiteral(joint: Joint): string | null {
  const rec: Record<string, number | undefined> = {
    raiseSide: joint.raiseSide || undefined,
    raiseFwd: joint.raiseFwd || undefined,
    bend: joint.bend || undefined,
    twist: joint.twist || undefined,
  };
  const body = obj(rec);
  return body === '' ? null : body;
}

/** Build the `pose: { … }` fragment, omitting neutral joints and an all-neutral
 *  pose entirely. Returns '' when nothing to emit. */
function poseFragment(spec: CharacterSpec): string {
  const p = spec.pose;
  const parts: string[] = [];
  const add = (name: string, lit: string | null) => { if (lit) parts.push(`    ${name}: ${lit},`); };
  add('armL', jointLiteral(p.armL));
  add('armR', jointLiteral(p.armR));
  add('legL', jointLiteral(p.legL));
  add('legR', jointLiteral(p.legR));
  const spine = obj({ lean: p.spine.lean || undefined, turn: p.spine.turn || undefined, side: p.spine.side || undefined });
  if (spine) parts.push(`    spine: ${spine},`);
  const head = obj({ yaw: p.head.yaw || undefined, pitch: p.head.pitch || undefined, roll: p.head.roll || undefined });
  if (head) parts.push(`    head: ${head},`);
  if (parts.length === 0) return '';
  return `\n  pose: {\n${parts.join('\n')}\n  },`;
}

/** Generate complete, runnable figure code for a spec. */
export function specToCode(spec: CharacterSpec): string {
  const { body, face, hair, clothing, colors } = spec;
  const L: string[] = [];

  L.push(encodeSpecComment(spec));
  L.push('// Generated by Character Creator — edit freely, or re-open Tools ▸ Character to keep tweaking.');
  L.push('const { sdf } = api;');
  L.push('const F = sdf.figure;');
  L.push('');

  // RIG — body proportions + pose. bust/belly only when set (default 0).
  const rigOpts: string[] = [
    `  height: ${fmt(body.height)},`,
    `  headsTall: ${fmt(body.headsTall)},`,
    `  build: ${fmt(body.build)},`,
    `  sex: ${fmt(body.sex)},`,
    `  age: ${fmt(body.age)},`,
    `  weight: ${fmt(body.weight)},`,
    `  muscle: ${fmt(body.muscle)},`,
  ];
  if (body.bust) rigOpts.push(`  bust: ${fmt(body.bust)},`);
  if (body.belly) rigOpts.push(`  belly: ${fmt(body.belly)},`);
  L.push(`const rig = F.rig({\n${rigOpts.join('\n')}${poseFragment(spec)}\n});`);
  L.push('');

  // HEAD + FACE — eyes/mouth left off the assemble so they become their own
  // top-level paint labels; nose/ears/brows shape come from the spec.
  L.push(`const head = F.head(rig, { faceShape: ${fmt(face.shape)} });`);
  L.push(`const face = F.face.assemble(head, rig, { eyes: false, nose: { type: ${fmt(face.nose)} }, mouth: false, ears: { type: ${fmt(face.ears)} } });`);
  L.push('');

  // SKIN — weld the body masses under one soft join.
  L.push('const skin = F.weld(rig, [');
  L.push('  F.torso(rig),');
  L.push('  F.neck(rig),');
  L.push('  F.arms(rig),');
  L.push("  F.hands(rig, { grip: 'relaxed' }),");
  L.push('  F.legs(rig),');
  L.push('  F.feet(rig),');
  L.push('  face,');
  L.push("]).label('skin');");
  L.push('');

  // Top-level paintable face features.
  const unionMembers: string[] = ['skin'];
  L.push(`const eyes = F.face.eyes(rig, { lids: ${fmt(face.lids)}, gaze: ${fmt(face.gaze)} });`);
  unionMembers.push('eyes');
  L.push(`const lips = F.face.mouthAccents(rig, { style: 'lips', lipShape: ${fmt(face.lipShape)}, expression: ${fmt(face.expression)} });`);
  unionMembers.push('lips');
  L.push(`const brows = F.face.brows(rig, { shape: ${fmt(face.brows)} }).label('brows');`);
  unionMembers.push('brows');

  // Hair (omitted entirely when bald).
  if (hair.style !== 'bald') {
    const hairOpts = obj({ style: hair.style, length: hair.length, volume: hair.volume !== 1 ? hair.volume : undefined });
    L.push(`const hair = F.hair(rig, ${hairOpts}).label('hair');`);
    unionMembers.push('hair');
  }

  // Clothing.
  if (clothing.top.on) {
    const topRec: Record<string, number | string | undefined> = { sleeve: clothing.top.sleeve };
    // A dress drops the hem to mid-thigh (figure API reads hemZ as an absolute
    // Z; derive it from the rig joints so it tracks proportions).
    if (clothing.top.length === 'dress') {
      L.push(`const dressHemZ = rig.joints.lowerLegL[2] + (rig.joints.hips[2] - rig.joints.lowerLegL[2]) * 0.45;`);
      L.push(`const top = F.clothing.top(rig, { sleeve: ${fmt(clothing.top.sleeve)}, hemZ: dressHemZ }).label('top');`);
    } else {
      L.push(`const top = F.clothing.top(rig, ${obj(topRec)}).label('top');`);
    }
    unionMembers.push('top');
  }
  if (clothing.pants.on) {
    const pantsOpts = obj({ leg: clothing.pants.leg, rise: clothing.pants.rise, length: clothing.pants.length });
    L.push(`const pants = F.clothing.pants(rig, ${pantsOpts}).label('pants');`);
    unionMembers.push('pants');
  }
  if (clothing.feet.on) {
    const fn = clothing.feet.kind === 'boots' ? 'boots' : 'shoes';
    L.push(`const feet = F.clothing.${fn}(rig, { label: 'feet' });`);
    unionMembers.push('feet');
  }
  if (spec.base) {
    L.push(`const base = F.base(rig).label('base');`);
    unionMembers.push('base');
  }
  L.push('');

  // PAINT — declared in code so colours persist with the saved version and
  // round-trip through the panel. Only emit labels that exist in this build.
  const paint: Array<[string, string]> = [
    ['skin', colors.skin],
    // `F.face.eyes` emits a skin-coloured eyelid region ('lids') for every lid
    // style except 'none'; paint it skin so it doesn't render as a grey patch.
    ['lids', colors.skin],
    ['eyes', colors.eyes],
    ['iris', colors.iris],
    ['pupil', colors.pupil],
    ['lips', colors.lips],
    ['brows', colors.brows],
  ];
  if (hair.style !== 'bald') paint.push(['hair', colors.hair]);
  if (clothing.top.on) paint.push(['top', colors.top]);
  if (clothing.pants.on) paint.push(['pants', colors.pants]);
  if (clothing.feet.on) { paint.push(['feet', colors.feet]); paint.push(['sole', colors.feet]); }
  if (spec.base) paint.push(['base', colors.base]);
  for (const [label, color] of paint) L.push(`api.paint.label(${fmt(label)}, ${fmt(color)});`);
  L.push('');

  // BUILD — finer face + hand grids via detail regions.
  L.push(`return sdf.union(${unionMembers.join(', ')})`);
  L.push('  .build({ edgeLength: 0.55, detail: [...F.faceDetail(rig), ...F.handDetail(rig)] });');

  return L.join('\n') + '\n';
}
