// Surface Nets — a smooth, manifold mesh straight from voxel occupancy.
//
// Where `taubinSmooth` rounds the *block* mesh (it nudges the existing cube
// corners, so it needs supersampling to get meaningful curvature and still
// reads faceted), Surface Nets builds a genuinely smooth surface at the grid's
// native resolution: it places ONE vertex per boundary-straddling cell — the
// average of the cube's surface-crossing edges — and stitches neighbouring
// vertices into quads. The result is lower-poly than supersampled Taubin yet
// noticeably rounder, and it's watertight by construction.
//
// This is the dual-contouring-family "naive Surface Nets" (S.F. Gibson, 1998),
// using the compact cube-edge / edge-crossing tables popularised by
// mikolalysenko's `isosurface`. The scalar field is binary occupancy sampled at
// voxel centres, so every surface crossing is exactly the edge midpoint.
//
// Colour: each quad is generated by one sign-changing lattice edge whose solid
// end is an occupied voxel — that voxel's colour flat-fills the quad, so the
// output slots straight into the per-triangle `triColors` pipeline the block
// mesher already feeds (no per-vertex colour needed).
//
// Pure logic (no DOM/WASM): unit-tested in the vitest tier.

import type { MeshData } from '../types';
import { VoxelGrid, colorComponents } from './grid';

// Standard Surface Nets tables, computed once. `cubeEdges` lists the 12 cube
// edges as ordered corner-index pairs; `edgeTable[mask]` is the bitmask of which
// of those 12 edges have a sign change for a given 8-corner occupancy `mask`.
const cubeEdges = new Int32Array(24);
const edgeTable = new Int32Array(256);
(function initTables() {
  let k = 0;
  for (let i = 0; i < 8; i++) {
    for (let j = 1; j <= 4; j <<= 1) {
      const p = i ^ j;
      if (i <= p) { cubeEdges[k++] = i; cubeEdges[k++] = p; }
    }
  }
  for (let i = 0; i < 256; i++) {
    let em = 0;
    for (let j = 0; j < 24; j += 2) {
      const a = !!(i & (1 << cubeEdges[j]));
      const b = !!(i & (1 << cubeEdges[j + 1]));
      em |= a !== b ? (1 << (j >> 1)) : 0;
    }
    edgeTable[i] = em;
  }
})();

/** Mesh a voxel grid with Surface Nets, returning smooth, welded `MeshData`
 *  with per-triangle colors. Returns an empty mesh for an empty grid. The
 *  surface is centred on voxel centres, so a solid box [min..max] yields a
 *  rounded form spanning roughly [min+0.5 .. max+0.5] — slightly inset from the
 *  blocky [min .. max+1], which is inherent to the rounding. */
export function surfaceNetsMesh(grid: VoxelGrid): MeshData {
  const bounds = grid.bounds();
  if (!bounds) return emptyMesh();

  // Sample lattice: occupancy at voxel centres, padded by one empty cell on
  // every side so boundary voxels generate their outward faces. Sample index
  // (i,j,k) maps to voxel coordinate (ox+i, oy+j, oz+k).
  const ox = bounds.min[0] - 1, oy = bounds.min[1] - 1, oz = bounds.min[2] - 1;
  const nx = bounds.max[0] - bounds.min[0] + 3;
  const ny = bounds.max[1] - bounds.min[1] + 3;
  const nz = bounds.max[2] - bounds.min[2] + 3;
  const total = nx * ny * nz;
  const sidx = (i: number, j: number, k: number) => (k * ny + j) * nx + i;

  const occ = new Uint8Array(total);          // 1 = solid voxel sample
  const col = new Int32Array(total).fill(-1);  // packed rgb for solid samples
  grid.forEach((x, y, z, rgb) => {
    const id = sidx(x - ox, y - oy, z - oz);
    occ[id] = 1;
    col[id] = rgb;
  });

  const positions: number[] = [];
  const tris: number[] = [];
  const triColors: number[] = [];
  const vmap = new Int32Array(total).fill(-1); // surface-vertex id per cube base sample
  // Linear-index steps for a -1 move along each axis (used to reach the three
  // already-visited neighbour cubes that share a sign-changing edge).
  const STEP = [1, nx, nx * ny];

  for (let k = 0; k < nz - 1; k++) {
    for (let j = 0; j < ny - 1; j++) {
      for (let i = 0; i < nx - 1; i++) {
        // 8-corner occupancy mask. Corner g has offset (g&1, (g>>1)&1, (g>>2)&1).
        let mask = 0;
        for (let g = 0; g < 8; g++) {
          if (occ[sidx(i + (g & 1), j + ((g >> 1) & 1), k + ((g >> 2) & 1))]) mask |= 1 << g;
        }
        if (mask === 0 || mask === 0xff) continue; // fully inside or outside → no surface here

        // Vertex = mean of this cube's surface-crossing edge points. The field
        // is binary, so every crossing sits at the edge midpoint (t = 0.5).
        const em = edgeTable[mask];
        let vx = 0, vy = 0, vz = 0, ec = 0;
        for (let e = 0; e < 12; e++) {
          if (!(em & (1 << e))) continue;
          const e0 = cubeEdges[e << 1], e1 = cubeEdges[(e << 1) + 1];
          // Accumulate each axis offset of the crossing point within the unit cube.
          vx += offsetContribution(e0, e1, 1);
          vy += offsetContribution(e0, e1, 2);
          vz += offsetContribution(e0, e1, 4);
          ec++;
        }
        const inv = 1 / ec;
        const m = sidx(i, j, k);
        vmap[m] = positions.length / 3;
        // Sample index → world: voxel coord (o+idx) has its centre at +0.5.
        positions.push(
          i + vx * inv + ox + 0.5,
          j + vy * inv + oy + 0.5,
          k + vz * inv + oz + 0.5,
        );

        // Emit a quad for each of the three minimal edges (corner 0 → +axis)
        // that changes sign, stitching the four cubes around that edge. The
        // perpendicular neighbour cubes were visited earlier, so their vertices
        // exist (an edge crossing means all four sharing cubes straddle it).
        for (let axis = 0; axis < 3; axis++) {
          if (!(em & (1 << axis))) continue;
          const iu = (axis + 1) % 3, iv = (axis + 2) % 3;
          // Need a previous cube along both perpendicular axes (else the
          // neighbour vertices this quad references don't exist yet).
          if (ijkAxis(i, j, k, iu) === 0 || ijkAxis(i, j, k, iv) === 0) continue;
          const du = STEP[iu], dv = STEP[iv];
          const v0 = vmap[m], vU = vmap[m - du], vV = vmap[m - dv], vUV = vmap[m - du - dv];
          if (v0 < 0 || vU < 0 || vV < 0 || vUV < 0) continue;

          // Colour from the solid end of the minimal edge: corner 0, else the
          // corner one step along `axis`.
          const corner0Solid = mask & 1;
          const rgb = corner0Solid
            ? col[m]
            : col[sidx(i + (axis === 0 ? 1 : 0), j + (axis === 1 ? 1 : 0), k + (axis === 2 ? 1 : 0))];
          const [r, g, b] = colorComponents(rgb < 0 ? 0 : rgb);

          // Wind the quad so the normal faces the empty side.
          if (corner0Solid) tris.push(v0, vU, vUV, v0, vUV, vV);
          else tris.push(v0, vV, vUV, v0, vUV, vU);
          triColors.push(r, g, b, r, g, b);
        }
      }
    }
  }

  const numTri = tris.length / 3;
  const triColorArr = Uint8Array.from(triColors);
  // Mark every triangle painted (see gridToMeshData for the why) so the color
  // pipeline never recolors a legitimately-black voxel to default blue.
  (triColorArr as Uint8Array & { _painted?: Uint8Array })._painted = new Uint8Array(numTri).fill(1);

  return {
    vertProperties: Float32Array.from(positions),
    triVerts: Uint32Array.from(tris),
    numVert: positions.length / 3,
    numTri,
    numProp: 3,
    triColors: triColorArr,
  };
}

/** Per-axis offset (0, 0.5, or 1) of a sign-changing edge's midpoint within the
 *  unit cube. `axisBit` is 1/2/4 for x/y/z. When the edge's two corners differ
 *  in that axis bit the crossing is the midpoint (0.5); otherwise both share the
 *  bit, contributing 1 (set) or 0 (clear). */
function offsetContribution(e0: number, e1: number, axisBit: number): number {
  const a = e0 & axisBit, b = e1 & axisBit;
  if (a !== b) return 0.5;
  return a ? 1 : 0;
}

/** The cube base index along a given axis (0=x, 1=y, 2=z). */
function ijkAxis(i: number, j: number, k: number, axis: number): number {
  return axis === 0 ? i : axis === 1 ? j : k;
}

function emptyMesh(): MeshData {
  const triColorArr = new Uint8Array(0);
  (triColorArr as Uint8Array & { _painted?: Uint8Array })._painted = new Uint8Array(0);
  return {
    vertProperties: new Float32Array(0),
    triVerts: new Uint32Array(0),
    numVert: 0,
    numTri: 0,
    numProp: 3,
    triColors: triColorArr,
  };
}
