// Self-Modeling Studio — pure state model.
//
// The Studio drives the multi-view reconstruction pipeline: a source photo →
// a turntable of alternate-angle images (generated by Gemini "nano banana" or
// uploaded by hand) → a silhouette carve (partwright.reconstructFromSilhouettes)
// → a voxel session. This module is the dependency-free core: angle presets,
// the image-model prompt text, building the carve input, and (de)serializing the
// whole studio so an import can be reopened without re-calling Gemini.
//
// Pure logic (no DOM, no network) — unit-tested in the vitest tier.

/** Camera angle for one view. Degrees, renderer convention: azimuth 0 = front
 *  (+Y), 90 = right (+X), 180 = back, 270 = left; elevation 0 = horizon. */
export interface StudioAngle {
  azimuth: number;
  elevation: number;
  /** Human-friendly caption derived from the angle (e.g. "Front", "Right"). */
  label: string;
}

export type ViewStatus = 'empty' | 'generating' | 'ready' | 'error';

export interface StudioView {
  /** Stable id (also the turntable slot key). */
  id: string;
  angle: StudioAngle;
  /** data URL of the image for this angle, or null until generated/uploaded. */
  src: string | null;
  /** Where the image came from. The Front view is the user's source photo. */
  origin: 'source' | 'gemini' | 'upload';
  /** Whether this view feeds the carve. */
  include: boolean;
  status: ViewStatus;
  error?: string;
}

export interface CarveSettings {
  resolution: number;
  smooth: number;
  frameFill: number;
  colorFromViews: boolean;
}

export interface StudioState {
  /** The source photo's media type (the image itself lives in the Front view). */
  sourceMediaType: string | null;
  views: StudioView[];
  carve: CarveSettings;
  /** Chosen Gemini image model id (null until resolved). */
  model: string | null;
  /** Which angle-set preset the views were built from. */
  preset: AnglePreset;
  /** How literal/polished a result to aim for (drives the brief). */
  style: BustStyle;
}

export const DEFAULT_CARVE: CarveSettings = {
  resolution: 96,
  smooth: 2,
  frameFill: 1,
  colorFromViews: true,
};

/** Cardinal/intercardinal label for an azimuth (0 = Front, clockwise). */
function azimuthLabel(azimuth: number): string {
  const a = ((azimuth % 360) + 360) % 360;
  const names = ['Front', 'Front-right', 'Right', 'Back-right', 'Back', 'Back-left', 'Left', 'Front-left'];
  // Snap to the nearest 45° bucket for naming; fall back to a degree label.
  const bucket = Math.round(a / 45);
  if (Math.abs(a - bucket * 45) < 1) return names[bucket % 8];
  return `Azimuth ${Math.round(a)}°`;
}

function angleLabel(azimuth: number, elevation: number): string {
  const base = azimuthLabel(azimuth);
  if (elevation >= 45) return base === 'Front' ? 'Top' : `${base} (high)`;
  if (elevation <= -45) return base === 'Front' ? 'Bottom' : `${base} (low)`;
  if (elevation >= 15) return `${base} (above)`;
  if (elevation <= -15) return `${base} (below)`;
  return base;
}

function makeAngle(azimuth: number, elevation: number): StudioAngle {
  return { azimuth, elevation, label: angleLabel(azimuth, elevation) };
}

/** Which set of angles the studio gathers. */
export type AnglePreset = 'portrait' | 'cardinal' | 'isometric' | 'full';

/** Dropdown options (order = display order; first is the default). */
export const ANGLE_PRESETS: { id: AnglePreset; label: string }[] = [
  { id: 'portrait', label: 'Portrait — 5 views (front · profiles · 3/4)' },
  { id: 'cardinal', label: 'Cardinal — 6 views (front · sides · back · top · bottom)' },
  { id: 'isometric', label: 'Isometric — 6 angled 3/4 views' },
  { id: 'full', label: 'Full turntable — 13 views' },
];

/** The angle set for a preset. Every preset starts with Front (az0/el0) — the
 *  slot the source photo fills. Poles stay at ±80° (90° is gimbal-degenerate). */
export function presetAngles(preset: AnglePreset): StudioAngle[] {
  switch (preset) {
    case 'portrait':
      // Faces/people: only the front hemisphere, which an image model can
      // synthesize reliably from one photo. The back/top/bottom of a head are
      // pure invention and tend to mislead, so they're deliberately excluded.
      return [
        makeAngle(0, 0), makeAngle(90, 0), makeAngle(270, 0),
        makeAngle(45, 15), makeAngle(315, 15),
      ];
    case 'cardinal':
      return [
        makeAngle(0, 0), makeAngle(90, 0), makeAngle(180, 0), makeAngle(270, 0),
        makeAngle(0, 80), makeAngle(0, -80),
      ];
    case 'isometric':
      return [
        makeAngle(0, 0),
        makeAngle(45, 30), makeAngle(135, 30), makeAngle(225, 30), makeAngle(315, 30),
        makeAngle(0, 60),
      ];
    case 'full':
    default: {
      const angles: StudioAngle[] = [];
      for (let i = 0; i < 12; i++) angles.push(makeAngle(Math.round(30 * i), 0));
      angles.push(makeAngle(0, 75)); // top cap
      return angles;
    }
  }
}

/** How polished/literal a result to aim for — the user's "cartoon vs realistic"
 *  lever. Drives the modeling brief. */
export type BustStyle = 'stylized' | 'lowpoly' | 'realistic';

export const BUST_STYLES: { id: BustStyle; label: string }[] = [
  { id: 'stylized', label: 'Stylized bust (recommended)' },
  { id: 'lowpoly', label: 'Low-poly' },
  { id: 'realistic', label: 'Realistic attempt' },
];

let _idCounter = 0;
function nextId(): string { return `v${(_idCounter++).toString(36)}_${Math.random().toString(36).slice(2, 7)}`; }

function viewsForPreset(preset: AnglePreset, prev?: StudioView[]): StudioView[] {
  return presetAngles(preset).map((angle, i) => {
    // Carry over a matching existing view's image (same angle) when switching
    // presets, so the source photo and any overlapping generations survive.
    const match = prev?.find(v => v.angle.azimuth === angle.azimuth && v.angle.elevation === angle.elevation);
    const origin: StudioView['origin'] = i === 0
      ? 'source'
      : (match && match.origin !== 'source' ? match.origin : 'gemini');
    return {
      id: nextId(),
      angle,
      src: match?.src ?? null,
      origin,
      include: match?.include ?? true,
      status: match?.src ? 'ready' : 'empty',
    };
  });
}

/** Fresh studio for a preset. The first view (Front, az0/el0) is the slot the
 *  source photo fills; all others start empty. */
export function newStudioState(preset: AnglePreset = 'portrait'): StudioState {
  return { sourceMediaType: null, views: viewsForPreset(preset), carve: { ...DEFAULT_CARVE }, model: null, preset, style: 'stylized' };
}

/** Switch the angle-set preset in place, preserving images for angles that
 *  carry over (and the source photo). */
export function setPreset(state: StudioState, preset: AnglePreset): void {
  state.views = viewsForPreset(preset, state.views);
  state.preset = preset;
}

/** The Front (source) view, if present. */
export function frontView(state: StudioState): StudioView | undefined {
  return state.views.find(v => v.origin === 'source')
    ?? state.views.find(v => v.angle.azimuth === 0 && v.angle.elevation === 0);
}

/**
 * Instruction for an image model to re-render the source subject from a target
 * angle. Emphasizes identity + a consistent, centred, same-scale framing on a
 * plain background — the conditions the silhouette carve relies on.
 */
export function anglePrompt(angle: StudioAngle): string {
  const a = ((angle.azimuth % 360) + 360) % 360;
  let view: string;
  if (a < 23 || a >= 338) view = 'directly from the front';
  else if (a < 68) view = 'from the front-right, turned 45 degrees';
  else if (a < 113) view = 'from the right side (full profile)';
  else if (a < 158) view = 'from the back-right, turned 135 degrees';
  else if (a < 203) view = 'directly from behind';
  else if (a < 248) view = 'from the back-left';
  else if (a < 293) view = 'from the left side (full profile)';
  else view = 'from the front-left, turned 315 degrees';
  const tilt = angle.elevation >= 45 ? ', looking down from high above (top-down view)'
    : angle.elevation >= 15 ? ', viewed slightly from above'
    : angle.elevation <= -15 ? ', viewed slightly from below' : '';
  return [
    `Using the provided image as the reference, generate a new image of the EXACT SAME subject viewed ${view}${tilt}.`,
    'Preserve the identity, proportions, hairstyle, clothing, and colours precisely — it must be recognizably the same subject.',
    'Show the entire subject, centred, at the same scale and vertical position as the source, on a plain flat neutral-grey background with even lighting.',
    'No cropping, no text, no props, no shadows on the background. The silhouette/outline accuracy matters most.',
  ].join(' ');
}

/** Views that will feed the carve: included, ready, and with an image. */
export function carveableViews(state: StudioState): StudioView[] {
  return state.views.filter(v => v.include && v.status === 'ready' && !!v.src);
}

/** Build the argument for `partwright.reconstructFromSilhouettes`. */
export function buildReconInput(state: StudioState): {
  views: Array<{ src: string; azimuth: number; elevation: number }>;
  options: CarveSettings;
} {
  return {
    views: carveableViews(state).map(v => ({ src: v.src!, azimuth: v.angle.azimuth, elevation: v.angle.elevation })),
    options: { ...state.carve },
  };
}

/** How many views are ready to use, and whether that's enough to proceed. */
export function readiness(state: StudioState): { ready: number; total: number; canBuild: boolean } {
  const ready = carveableViews(state).length;
  return { ready, total: state.views.length, canBuild: ready >= 2 };
}

/** The included, ready views as reference images (src + angle caption) to
 *  attach to the session for the AI to study. */
export function referenceImages(state: StudioState): Array<{ src: string; label: string }> {
  return carveableViews(state).map(v => ({ src: v.src!, label: v.angle.label }));
}

/**
 * The modeling brief handed to the in-app AI: a prompt that lists the attached
 * reference angles and asks the AI to build a matching 3D model with the
 * partwright tools, choosing whichever engine fits the form and iterating
 * against the references with renderViews. (Populated into the chat input — the
 * user reviews and sends it; nothing auto-runs.)
 */
export function buildModelingBrief(state: StudioState): string {
  const views = carveableViews(state);
  const lines = views
    .map(v => `- ${v.angle.label} — azimuth ${v.angle.azimuth}°, elevation ${v.angle.elevation}°`)
    .join('\n');

  // What to aim for, by style. Stylization is deliberate: an LLM authoring
  // geometry can't hit photoreal anatomy, so a clean stylized bust reads as
  // intentional rather than uncanny.
  const goal: Record<BustStyle, string> = {
    stylized: 'Build a STYLIZED 3D character bust (head, neck, and shoulders) that is recognizably this person — like a polished game / animation character. Capture the IDENTIFYING features: overall head and face proportions, hairstyle, beard shape, any hat/glasses, and the main skin / hair / clothing colors. Do NOT attempt photoreal skin or tiny details; a clean, appealing, slightly simplified likeness is the goal.',
    lowpoly: 'Build a clean LOW-POLY bust (head, neck, and shoulders): bold simplified forms, faceted planes, flat-shaded colour regions. Capture the person\'s silhouette, proportions, hair/beard masses, any hat, and main colours — not fine detail.',
    realistic: 'Attempt a realistic likeness bust (head, neck, and shoulders). This is hard for code-authored geometry, so expect an approximation: prioritise correct proportions and smooth organic surfaces over fine detail.',
  };

  return [
    `A labeled grid of ${views.length} reference views of one person (front hemisphere) is attached to THIS message — and the same views are in the Images tab:`,
    lines,
    '',
    'IMPORTANT: actually look at the attached reference grid (call getReferenceImages anytime to see it again). If you cannot see it, STOP and tell me — do not invent a subject. Replace any placeholder/starter model in the editor.',
    '',
    goal[state.style],
    '',
    'Engine + technique: use the manifold-js (mesh) engine — best for organic heads. Start from an ellipsoid/sphere head; build the left/right halves by MIRRORING across the X plane so the face is symmetric; blend features into the head with smooth unions (SDF / levelSet / warp / smoothOut) rather than leaving hard primitive intersections sticking out. Keep it a single connected, watertight mesh.',
    '',
    'Work in stages and VERIFY each with renderView BEFORE moving on — most failures come from skipping this:',
    '1. Block in just the head + neck + shoulders mass. renderView front (az0) and right (az90); match the silhouette and proportions to the references. Do not add anything until the basic head shape is right.',
    '2. Add the hair and beard as their own masses sized to the references, then the hat (if any) — the hat sits ON TOP of the skull ABOVE the brow line and must never cover the eyes or forehead. renderView and fix placement.',
    '3. Add facial features — brow, nose, eye sockets + eyes, lips — as small SYMMETRIC additions/indentations. Keep them subtle. renderView front and confirm the eyes and mouth are actually visible and correctly placed.',
    '4. Colour LAST, as broad regions matching the references: skin, hair, beard, hat, clothing each get their own region with correct boundaries — e.g. the hat colour belongs ONLY on the hat, never bleeding onto the forehead or eyes.',
    '',
    'After each stage compare your render to the matching reference angle and fix proportions before adding more. Save progress with runAndSave; note decisions with addSessionNote.',
  ].join('\n');
}

/**
 * Spec-driven modeling prompt (no reference image attached): wraps a build spec
 * produced by a vision model with the engine/technique + staged verify loop, so
 * the modeling AI follows an explicit recipe rather than raw pixels.
 */
export function buildSpecModelingPrompt(spec: string, style: BustStyle): string {
  const aim: Record<BustStyle, string> = {
    stylized: 'a clean STYLIZED character bust',
    lowpoly: 'a clean LOW-POLY bust',
    realistic: 'a realistic-attempt bust',
  };
  return [
    `Build ${aim[style]} (head, neck, and shoulders) of a person from the BUILD SPEC below, using the partwright tools. There is NO reference image — follow the spec precisely; if something isn't specified, choose sensible, symmetric defaults.`,
    '',
    '=== BUILD SPEC ===',
    spec.trim(),
    '=== END SPEC ===',
    '',
    'Engine + technique: use the manifold-js (mesh) engine. Build the head from an ellipsoid; MIRROR across the X plane for symmetry; blend features into the head with smooth unions (SDF / levelSet / warp / smoothOut), not hard primitive intersections; keep it one connected, watertight mesh.',
    '',
    'Work in stages and VERIFY each with renderView before moving on:',
    '1. Block in the head + neck + shoulders mass to the spec\'s proportions; renderView front (az0) and right (az90); fix proportions before adding anything.',
    '2. Add hair and beard, then any hat — the hat sits ABOVE the brow line and must never cover the eyes or forehead. renderView; fix placement.',
    '3. Add features (brow, nose, eye sockets + eyes, lips) as small SYMMETRIC additions; renderView front and confirm the eyes and mouth are visible and correctly placed.',
    '4. Colour LAST, as broad regions per the spec — each colour stays within its region (the hat colour belongs ONLY on the hat).',
    '',
    'After each stage compare your render to the spec and fix before adding more. Save progress with runAndSave; note decisions with addSessionNote.',
  ].join('\n');
}

// ── Persistence ─────────────────────────────────────────────────────────────
// Serialized form stored on the session (Session.studioImport). Images ride
// along inline as data URLs so reopening the import needs no Gemini calls. Kept
// as a plain JSON-safe record, versioned for forward migration.

export interface StudioImportRecord {
  v: 1;
  sourceMediaType: string | null;
  model: string | null;
  preset?: AnglePreset;
  style?: BustStyle;
  carve: CarveSettings;
  views: Array<{
    azimuth: number; elevation: number; label: string;
    src: string | null; origin: StudioView['origin']; include: boolean; status: ViewStatus;
  }>;
}

export function serializeStudio(state: StudioState): StudioImportRecord {
  return {
    v: 1,
    sourceMediaType: state.sourceMediaType,
    model: state.model,
    preset: state.preset,
    style: state.style,
    carve: { ...state.carve },
    views: state.views.map(v => ({
      azimuth: v.angle.azimuth, elevation: v.angle.elevation, label: v.angle.label,
      src: v.src, origin: v.origin, include: v.include,
      // Don't persist a transient "generating" state as in-flight.
      status: v.status === 'generating' ? 'empty' : v.status,
    })),
  };
}

export function deserializeStudio(rec: StudioImportRecord): StudioState {
  return {
    sourceMediaType: rec.sourceMediaType ?? null,
    model: rec.model ?? null,
    preset: rec.preset ?? 'portrait',
    style: rec.style ?? 'stylized',
    carve: { ...DEFAULT_CARVE, ...rec.carve },
    views: rec.views.map(v => ({
      id: nextId(),
      angle: { azimuth: v.azimuth, elevation: v.elevation, label: v.label || angleLabel(v.azimuth, v.elevation) },
      src: v.src ?? null,
      origin: v.origin,
      include: v.include,
      status: v.status === 'generating' ? (v.src ? 'ready' : 'empty') : v.status,
    })),
  };
}
