// Self-Modeling Studio — pure state model.
//
// The Studio drives the multi-view reconstruction pipeline: a source photo →
// a turntable of alternate-angle images (generated by Gemini "nano banana" or
// uploaded by hand) → a silhouette carve (partwright.reconstructFromSilhouettes)
// → a voxel session. This module is the dependency-free core: angle presets,
// the image-model prompt text, building the carve input, and (de)serializing the
// whole studio so an import can be reopened without re-calling Gemini.
//
// Pure logic (no DOM, no network) — unit-tested in the vitest tier.

/** Camera angle for one view. Degrees, renderer convention: azimuth 0 = front
 *  (+Y), 90 = right (+X), 180 = back, 270 = left; elevation 0 = horizon. */
export interface StudioAngle {
  azimuth: number;
  elevation: number;
  /** Human-friendly caption derived from the angle (e.g. "Front", "Right"). */
  label: string;
}

export type ViewStatus = 'empty' | 'generating' | 'ready' | 'error';

export interface StudioView {
  /** Stable id (also the turntable slot key). */
  id: string;
  angle: StudioAngle;
  /** data URL of the image for this angle, or null until generated/uploaded. */
  src: string | null;
  /** Where the image came from. The Front view is the user's source photo. */
  origin: 'source' | 'gemini' | 'upload';
  /** Whether this view feeds the carve. */
  include: boolean;
  status: ViewStatus;
  error?: string;
}

export interface CarveSettings {
  resolution: number;
  smooth: number;
  frameFill: number;
  colorFromViews: boolean;
}

export interface StudioState {
  /** The source photo's media type (the image itself lives in the Front view). */
  sourceMediaType: string | null;
  views: StudioView[];
  carve: CarveSettings;
  /** Chosen Gemini image model id (null until resolved). */
  model: string | null;
}

export type TurntablePreset = 'quick8' | 'standard12' | 'detailed16';

export const DEFAULT_CARVE: CarveSettings = {
  resolution: 96,
  smooth: 2,
  frameFill: 1,
  colorFromViews: true,
};

/** Cardinal/intercardinal label for an azimuth (0 = Front, clockwise). */
function azimuthLabel(azimuth: number): string {
  const a = ((azimuth % 360) + 360) % 360;
  const names = ['Front', 'Front-right', 'Right', 'Back-right', 'Back', 'Back-left', 'Left', 'Front-left'];
  // Snap to the nearest 45° bucket for naming; fall back to a degree label.
  const bucket = Math.round(a / 45);
  if (Math.abs(a - bucket * 45) < 1) return names[bucket % 8];
  return `Azimuth ${Math.round(a)}°`;
}

function angleLabel(azimuth: number, elevation: number): string {
  const base = azimuthLabel(azimuth);
  if (elevation >= 45) return base === 'Front' ? 'Top' : `${base} (high)`;
  if (elevation >= 15) return `${base} (above)`;
  if (elevation <= -15) return `${base} (below)`;
  return base;
}

function makeAngle(azimuth: number, elevation: number): StudioAngle {
  return { azimuth, elevation, label: angleLabel(azimuth, elevation) };
}

/** The angle set for a preset: evenly spaced azimuths at the horizon plus a
 *  high "top" cap (a single photo rarely affords a true under-view). */
export function turntableAngles(preset: TurntablePreset): StudioAngle[] {
  const counts: Record<TurntablePreset, number> = { quick8: 8, standard12: 12, detailed16: 16 };
  const n = counts[preset];
  const angles: StudioAngle[] = [];
  for (let i = 0; i < n; i++) angles.push(makeAngle(Math.round((360 / n) * i), 0));
  angles.push(makeAngle(0, 75)); // top cap
  if (preset === 'detailed16') angles.push(makeAngle(45, 35)); // extra 3/4-high
  return angles;
}

let _idCounter = 0;
function nextId(): string { return `v${(_idCounter++).toString(36)}_${Math.random().toString(36).slice(2, 7)}`; }

/** Fresh studio for a preset. The first view (Front, az0/el0) is the slot the
 *  source photo fills; all others start empty. */
export function newStudioState(preset: TurntablePreset = 'standard12'): StudioState {
  const views: StudioView[] = turntableAngles(preset).map((angle, i) => ({
    id: nextId(),
    angle,
    src: null,
    origin: i === 0 ? 'source' : 'gemini',
    include: true,
    status: 'empty',
  }));
  return { sourceMediaType: null, views, carve: { ...DEFAULT_CARVE }, model: null };
}

/** The Front (source) view, if present. */
export function frontView(state: StudioState): StudioView | undefined {
  return state.views.find(v => v.origin === 'source')
    ?? state.views.find(v => v.angle.azimuth === 0 && v.angle.elevation === 0);
}

/**
 * Instruction for an image model to re-render the source subject from a target
 * angle. Emphasizes identity + a consistent, centred, same-scale framing on a
 * plain background — the conditions the silhouette carve relies on.
 */
export function anglePrompt(angle: StudioAngle): string {
  const a = ((angle.azimuth % 360) + 360) % 360;
  let view: string;
  if (a < 23 || a >= 338) view = 'directly from the front';
  else if (a < 68) view = 'from the front-right, turned 45 degrees';
  else if (a < 113) view = 'from the right side (full profile)';
  else if (a < 158) view = 'from the back-right, turned 135 degrees';
  else if (a < 203) view = 'directly from behind';
  else if (a < 248) view = 'from the back-left';
  else if (a < 293) view = 'from the left side (full profile)';
  else view = 'from the front-left, turned 315 degrees';
  const tilt = angle.elevation >= 45 ? ', looking down from high above (top-down view)'
    : angle.elevation >= 15 ? ', viewed slightly from above'
    : angle.elevation <= -15 ? ', viewed slightly from below' : '';
  return [
    `Using the provided image as the reference, generate a new image of the EXACT SAME subject viewed ${view}${tilt}.`,
    'Preserve the identity, proportions, hairstyle, clothing, and colours precisely — it must be recognizably the same subject.',
    'Show the entire subject, centred, at the same scale and vertical position as the source, on a plain flat neutral-grey background with even lighting.',
    'No cropping, no text, no props, no shadows on the background. The silhouette/outline accuracy matters most.',
  ].join(' ');
}

/** Views that will feed the carve: included, ready, and with an image. */
export function carveableViews(state: StudioState): StudioView[] {
  return state.views.filter(v => v.include && v.status === 'ready' && !!v.src);
}

/** Build the argument for `partwright.reconstructFromSilhouettes`. */
export function buildReconInput(state: StudioState): {
  views: Array<{ src: string; azimuth: number; elevation: number }>;
  options: CarveSettings;
} {
  return {
    views: carveableViews(state).map(v => ({ src: v.src!, azimuth: v.angle.azimuth, elevation: v.angle.elevation })),
    options: { ...state.carve },
  };
}

/** How many views are ready to use, and whether that's enough to proceed. */
export function readiness(state: StudioState): { ready: number; total: number; canBuild: boolean } {
  const ready = carveableViews(state).length;
  return { ready, total: state.views.length, canBuild: ready >= 2 };
}

/** The included, ready views as reference images (src + angle caption) to
 *  attach to the session for the AI to study. */
export function referenceImages(state: StudioState): Array<{ src: string; label: string }> {
  return carveableViews(state).map(v => ({ src: v.src!, label: v.angle.label }));
}

/**
 * The modeling brief handed to the in-app AI: a prompt that lists the attached
 * reference angles and asks the AI to build a matching 3D model with the
 * partwright tools, choosing whichever engine fits the form and iterating
 * against the references with renderViews. (Populated into the chat input — the
 * user reviews and sends it; nothing auto-runs.)
 */
export function buildModelingBrief(state: StudioState): string {
  const views = carveableViews(state);
  const lines = views
    .map(v => `- ${v.angle.label} — azimuth ${v.angle.azimuth}°, elevation ${v.angle.elevation}°`)
    .join('\n');
  return [
    `I've attached ${views.length} reference views of one subject from different angles — they're attached directly to THIS message (and also in the Images tab):`,
    lines,
    '',
    'IMPORTANT: actually look at the attached images. If you cannot see them in your input, STOP and tell me they are missing — do not guess or invent a subject. Ignore any placeholder/starter model currently in the editor; replace it with your build.',
    '',
    'Please build a 3D model that matches this subject as closely as you can, using the partwright tools.',
    'Pick whichever engine best fits the form: manifold-js (mesh) for organic/curved shapes like faces and bodies (warp, levelSet, smoothOut help here); BREP/replicad for hard-surface CAD parts with exact fillets; OpenSCAD for parametric mechanical parts; voxel only if a blocky look is wanted.',
    'Work coarse-to-fine: block in the major masses and get the overall proportions and silhouette right first, then add detail.',
    'After each significant change, call renderViews (or renderView at the matching azimuth/elevation) and compare your render to the reference at that same angle — iterate until the silhouettes and proportions line up.',
    'Save progress with runAndSave, and record key decisions with addSessionNote.',
  ].join('\n');
}

// ── Persistence ─────────────────────────────────────────────────────────────
// Serialized form stored on the session (Session.studioImport). Images ride
// along inline as data URLs so reopening the import needs no Gemini calls. Kept
// as a plain JSON-safe record, versioned for forward migration.

export interface StudioImportRecord {
  v: 1;
  sourceMediaType: string | null;
  model: string | null;
  carve: CarveSettings;
  views: Array<{
    azimuth: number; elevation: number; label: string;
    src: string | null; origin: StudioView['origin']; include: boolean; status: ViewStatus;
  }>;
}

export function serializeStudio(state: StudioState): StudioImportRecord {
  return {
    v: 1,
    sourceMediaType: state.sourceMediaType,
    model: state.model,
    carve: { ...state.carve },
    views: state.views.map(v => ({
      azimuth: v.angle.azimuth, elevation: v.angle.elevation, label: v.angle.label,
      src: v.src, origin: v.origin, include: v.include,
      // Don't persist a transient "generating" state as in-flight.
      status: v.status === 'generating' ? 'empty' : v.status,
    })),
  };
}

export function deserializeStudio(rec: StudioImportRecord): StudioState {
  return {
    sourceMediaType: rec.sourceMediaType ?? null,
    model: rec.model ?? null,
    carve: { ...DEFAULT_CARVE, ...rec.carve },
    views: rec.views.map(v => ({
      id: nextId(),
      angle: { azimuth: v.azimuth, elevation: v.elevation, label: v.label || angleLabel(v.azimuth, v.elevation) },
      src: v.src ?? null,
      origin: v.origin,
      include: v.include,
      status: v.status === 'generating' ? (v.src ? 'ready' : 'empty') : v.status,
    })),
  };
}
