#!/usr/bin/env node
// snap — one-shot "navigate, settle, screenshot" for manual verification.
//
//   npm run snap -- [route] [--out file.png] [--wait ms] [--width N] [--height N] [--full]
//
//   npm run snap -- /editor
//   npm run snap -- "/editor?session=abc&v=3" --out test-results/v3.png --wait 6000
//   npm run snap -- /catalog --width 375 --height 812        # phone-width check
//
// Covers the no-interaction case of the manual-verification pattern in
// CLAUDE.md: when all you need is "load this route and show me", this saves
// writing (and deleting) a throwaway _scratch-*.spec.ts. Anything that needs
// clicks/typing still wants a real spec.
//
// Implementation: generates a temporary Playwright spec and runs it through
// `npx playwright test`, so the dev server auto-start, sandbox Chromium
// detection, and COEP/COOP headers from playwright.config.ts all apply.
import { spawnSync } from 'node:child_process';
import { writeFileSync, unlinkSync, mkdirSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function parseArgs(argv) {
  const a = { route: '/editor', out: 'test-results/snap.png', wait: 4000, width: null, height: null, full: false };
  for (let i = 0; i < argv.length; i++) {
    const t = argv[i];
    if (t === '--out') a.out = argv[++i];
    else if (t === '--wait') a.wait = parseInt(argv[++i], 10);
    else if (t === '--width') a.width = parseInt(argv[++i], 10);
    else if (t === '--height') a.height = parseInt(argv[++i], 10);
    else if (t === '--full') a.full = true;
    else if (t === '--help' || t === '-h') { usage(); process.exit(0); }
    else if (!t.startsWith('-')) a.route = t;
    else { console.error(`snap: unknown flag ${t}`); usage(); process.exit(2); }
  }
  if (!Number.isFinite(a.wait) || a.wait < 0) { console.error('snap: --wait expects a non-negative ms number'); process.exit(2); }
  return a;
}

function usage() {
  console.error('usage: npm run snap -- [route] [--out file.png] [--wait ms] [--width N] [--height N] [--full]');
}

const a = parseArgs(process.argv.slice(2));
const out = resolve(root, a.out);
mkdirSync(dirname(out), { recursive: true });

// Generous test timeout: settle wait + dev-server/WASM boot headroom.
const testTimeout = a.wait + 45_000;
const isEditor = a.route.startsWith('/editor');
const spec = `// Auto-generated by scripts/snap.mjs — deleted after the run.
import { test } from 'playwright/test';

test(${JSON.stringify(`snap: ${a.route}`)}, async ({ page }) => {
  test.setTimeout(${testTimeout});
  ${a.width && a.height ? `await page.setViewportSize({ width: ${a.width}, height: ${a.height} });` : ''}
  await page.goto(${JSON.stringify(a.route)});
  ${isEditor ? `// Editor route: wait past the WASM-boot splash (a fixed wait alone races
  // engine init on a loaded machine), then let the viewport settle.
  await page.waitForFunction(
    () => !!(window as unknown as { partwright?: { run?: unknown } }).partwright?.run,
    { timeout: 30_000 },
  ).catch(() => { /* screenshot whatever state we reached */ });` : ''}
  await page.waitForTimeout(${a.wait}); // settle (render, fonts, animations)
  await page.screenshot({ path: ${JSON.stringify(out)}, fullPage: ${a.full} });
});
`;

const specPath = join(root, 'tests', `_snap-${process.pid}.spec.ts`);
writeFileSync(specPath, spec);
let status = 1;
try {
  const r = spawnSync('npx', ['playwright', 'test', specPath], { cwd: root, stdio: 'inherit' });
  status = r.status ?? 1;
} finally {
  try { unlinkSync(specPath); } catch { /* already gone */ }
}
if (status === 0) console.log(JSON.stringify({ ok: true, png: out }));
else console.error(`snap: playwright run failed (exit ${status}) — screenshot may be missing`);
process.exit(status);
